Repository IbraDajani/pokedex, pull requests merged in 2022-07, with the labels that each got.

#3 Chore/add editor config file
  .editorconfig
  src/App.tsx
Labels: enhancement

#6 creat folder structure
  src/@types/.gitkeep
  src/assets/.gitkeep
  src/components/.gitkeep
  src/constants/.gitkeep
  src/navigation/.gitkeep
  src/screens/Home/.gitkeep
  src/screens/Internal/.gitkeep
  src/services/resource/.gitkeep
Labels: enhancement

#9 Feat: added separator component
  src/App.tsx
  src/components/Separator/index.tsx
  src/components/Separator/styles.ts
  src/components/Separator/types.ts
Labels: enhancement

#11 Feat/create-row-between-component
  src/App.tsx
  src/components/RowBetween/index.tsx
  src/components/RowBetween/styles.ts
  src/components/RowBetween/types.ts
Labels: enhancement

#13 Feat/create text component
  src/App.tsx
  src/components/Text/index.tsx
  src/components/Text/styles.ts
  src/components/Text/types.ts
Labels: enhancement

#14 Chore: Mocked API JSON on utils folder and created the pokemonDTO
  src/@types/dtos/pokemonDTO.ts
  src/utils/apiMockData.ts
Labels: documentation, enhancement

#18 Add navigation
  package.json
  src/App.tsx
  src/navigation/routes/index.tsx
  src/screens/Home/.gitkeep
  src/screens/Home/index.tsx
  src/screens/Internal/.gitkeep
  src/screens/Internal/index.tsx
  yarn.lock
Labels: enhancement

#19 Update README.md
  README.md
Labels: enhancement

#26 Feat: PokemonCard Compoment
  package.json
  src/@types/dtos/pokemonDTO.ts
  src/assets/.gitkeep
  src/assets/images/pokeball.png
  src/components/.gitkeep
  src/screens/Home/index.tsx
  src/screens/Home/localComponents/PokemonCard/index.tsx
  src/screens/Home/localComponents/PokemonCard/styles.ts
  src/screens/Home/localComponents/PokemonCard/types.ts
  src/screens/Home/localComponents/PokemonCard/usePokemonCardController.ts
  src/screens/Home/styles.ts
  src/screens/Internal/index.tsx
  src/screens/Internal/styles.ts
  src/utils/apiMockData.ts
  yarn.lock
Labels: enhancement

#27 Feat: Button component
  src/components/Button/index.tsx
  src/components/Button/styles.ts
  src/components/Button/types.ts
  src/screens/Home/index.tsx
Labels: enhancement

#25 Feat/create loading component
  .eslintrc.json
  android/app/build.gradle
  src/@types/images.d.ts
  src/assets/images/headerLogo.gif
  src/components/Button/styles.ts
  src/components/Loading/index.tsx
  src/components/Loading/types.tsx
  src/navigation/routes/index.tsx
  src/screens/Login/index.tsx
  src/screens/Login/styles.ts
Labels: enhancement

#35 Chore/add root import
  .eslintrc.json
  babel.config.js
  package.json
  src/components/Button/types.ts
  src/components/Icon/index.tsx
  src/components/Icon/types.ts
  src/components/Input/types.ts
  src/constants/icons.ts
  src/navigation/routes/index.tsx
  src/screens/Home/index.tsx
  src/screens/Home/localComponents/PokemonCard/index.tsx
  src/screens/Home/localComponents/PokemonCard/styles.ts
  src/screens/Home/localComponents/PokemonCard/types.ts
  src/screens/Internal/index.tsx
  src/screens/Login/index.tsx
  tsconfig.json
  yarn.lock
Labels: enhancement

#36 Chore/change pokemon images
  src/utils/apiMockData.ts
Labels: enhancement

#21 added login screen designer
  .eslintrc.json
  package.json
  src/assets/animations/pokeball.json
  src/assets/icons/google/Vector.png
  src/assets/icons/google/Vector@2x.png
  src/assets/icons/google/Vector@3x.png
  src/components/Button/index.tsx
  src/components/Button/styles.ts
  src/components/Button/types.ts
  src/constants/icons.ts
  src/screens/Login/index.tsx
  src/screens/Login/styles.ts
  yarn.lock
Labels: enhancement

#37 Feat: Added login with google
  android/app/build.gradle
  android/app/debug.keystore
  android/app/google-services.json
  android/build.gradle
  package.json
  src/screens/Login/index.tsx
  src/screens/Login/types.ts
  yarn.lock
Labels: enhancement

#38 feat: apk android
  android/app/build.gradle
  android/gradle.properties
Labels: release

#39 Feat/home screen
  src/assets/icons/logout/Vector.png
  src/assets/icons/logout/Vector@2x.png
  src/assets/icons/logout/Vector@3x.png
  src/constants/icons.ts
  src/navigation/routes/index.tsx
  src/screens/Home/index.tsx
  src/screens/Home/localComponents/HeaderLabel/index.tsx
  src/screens/Home/localComponents/HeaderLabel/styles.ts
  src/screens/Home/localComponents/PokemonCard/index.tsx
  src/screens/Home/localComponents/PokemonCard/styles.ts
  src/screens/Home/localComponents/PokemonCard/types.ts
  src/screens/Home/localComponents/PokemonCard/usePokemonCardController.ts
  src/screens/Home/styles.ts
  src/screens/Internal/index.tsx
  src/screens/Internal/styles.ts
  src/screens/Login/index.tsx
Labels: enhancement

#40 Feat Screens Gray
  src/screens/Home/styles.ts
  src/screens/Internal/styles.ts
  src/screens/Login/styles.ts
Labels: enhancement

#41 Feat/create signed in and sign in routes
  src/App.tsx
  src/components/Button/styles.ts
  src/navigation/SignInRoutes/index.tsx
  src/navigation/SignedInRoutes/index.tsx
  yarn.lock
Labels: enhancement

#42 removed login screen route from SignedInRoutes
  src/navigation/SignedInRoutes/index.tsx
Labels: enhancement

#44 Change Repeated Pokemon Image
  src/utils/apiMockData.ts
Labels: bug

#46 Chore Home Screen Responsive
  src/components/ButtonHeader/index.tsx
  src/components/Header/styles.ts
  src/screens/Home/index.tsx
  src/screens/Home/localComponents/PokemonCard/styles.ts
  src/screens/Home/styles.ts
  src/utils/apiMockData.ts
Labels: bug

#45 Feat: Added context, authHook and Login with google and logout too
  src/@types/dtos/user.d.ts
  src/App.tsx
  src/context/Auth/index.tsx
  src/context/Auth/types.ts
  src/hooks/useAuth/index.tsx
  src/navigation/.gitkeep
  src/navigation/index.tsx
  src/screens/Home/index.tsx
  src/screens/Login/index.tsx
Labels: enhancement

#47 Chore MVVM Architecture
  src/components/Button/index.tsx
  src/components/Button/useButtonController.ts
  src/components/Input/index.tsx
  src/components/Input/useInputController.tsx
  src/screens/Home/index.tsx
  src/screens/Internal/styles.ts
Labels: enhancement
